// AUTO-GENERATED by tools/bake_sprites.js — 勿手改, 改工具后重新烘焙。
#pragma once
#include <stdint.h>

typedef struct {
    uint16_t w;
    uint16_t h;
    const uint16_t *px; // RGB565, 0x0000 = 透明
} sprite_t;

extern const sprite_t spr_dino_0;
extern const sprite_t spr_dino_1;
extern const sprite_t spr_dino_2;
extern const sprite_t spr_dino_3;
extern const sprite_t spr_dino_4;
extern const sprite_t spr_dino_5;
extern const sprite_t spr_dino_6;
extern const sprite_t spr_dino_7;
extern const sprite_t spr_dino_down_0;
extern const sprite_t spr_dino_down_1;
extern const sprite_t spr_dino_down_2;
extern const sprite_t spr_dino_down_3;
extern const sprite_t spr_dino_down_4;
extern const sprite_t spr_dino_down_5;
extern const sprite_t spr_dino_down_6;
extern const sprite_t spr_dino_down_7;
extern const sprite_t spr_dino_dead;
extern const sprite_t spr_dino_dead_down;
extern const sprite_t spr_cactus;
extern const sprite_t spr_cactus_tall;
extern const sprite_t spr_cactus_thin;
extern const sprite_t spr_fcactus;
extern const sprite_t spr_fcactus_tall;
extern const sprite_t spr_fcactus_thin;
extern const sprite_t spr_ptero_0;
extern const sprite_t spr_ptero_1;
extern const sprite_t spr_rock_0;
extern const sprite_t spr_rock_1;
extern const sprite_t spr_rock_2;
extern const sprite_t spr_rock_3;
extern const sprite_t spr_rock_4;
extern const sprite_t spr_flower_0;
extern const sprite_t spr_flower_1;
extern const sprite_t spr_flower_2;
extern const sprite_t spr_skull;
extern const sprite_t spr_scorpion;
extern const sprite_t spr_tree_green_far;
extern const sprite_t spr_tree_dead_far;
extern const sprite_t spr_cactus_far_0;
extern const sprite_t spr_cactus_far_1;
extern const sprite_t spr_cactus_far_2;
extern const sprite_t spr_skull_far;
extern const sprite_t spr_tumbleweed_0;
extern const sprite_t spr_tumbleweed_1;
extern const sprite_t spr_tumbleweed_2;
extern const sprite_t spr_tumbleweed_3;
extern const sprite_t spr_tumbleweed_4;
extern const sprite_t spr_tumbleweed_5;
extern const sprite_t spr_tumbleweed_6;
extern const sprite_t spr_tumbleweed_7;
extern const sprite_t spr_heart;
